modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPL v3.0"
[[mods]]
modId="rotp_th"
version="${file.jarVersion}"
displayName="RotP The Hand"
logoFile="logo.png"
credits='''

  The Texture of the Hand: August_dr
  Stand sound effects:
    Passione Sound - https://www.youtube.com/channel/UC_Tm3UQEmNLEChxcfk5yqFw
  Translation files:
    Venezuelan Spanish: ElTormakzXD
    Chinese Simplified: Johnny_Joestar
'''
authors="DanielGamer321, StandoByte"
description='''
An addon for Ripples of the Past mod, adding a new Stand - The Hand.
'''
[[dependencies.rotp_th]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rotp_th]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rotp_th]]
    modId="jojo"
    mandatory=true
    versionRange="[0.2.2,0.3)"
    ordering="AFTER"
    side="BOTH"
